<a href="https://colab.research.google.com/github/seraxarah/DataAnalysis/blob/main/%EC%98%A4%ED%94%88%EC%86%8C%EC%8A%A4_%EB%8D%B0%EC%9D%B4%ED%84%B0_%EB%B6%84%EC%84%9D_6%EA%B0%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 오픈소스 기반 데이터 분석 6강 - 데이터 전처리 1

### 6-1 데이터 훑어보기

In [15]:
import pandas as pd
import numpy as np

data = {
    'name': ['김민수', '이지영', '박준호', '최서연', '정도윤'],
    'age': [25, 30, 28, 22, 35],
    'city': ['서울', '부산', '인천', '서울', '대전'],
    'score': [90, 85, 95, 80, np.nan]
}
df = pd.DataFrame(data)

## 데이터 측정
df.describe()

## 모든 데이터 타입 측정
df.describe(include = 'all')

## 수치형 데이터 측정
df.describe(include = [np.number])

## 범주형 데이터 측정
df.describe(include = ['object'])

## 특정 열 분석
df['score'].describe

<bound method NDFrame.describe of 0    90.0
1    85.0
2    95.0
3    80.0
4     NaN
Name: score, dtype: float64>

### 6-2 DataFrame 열 선택 및 **조작**

In [3]:
import pandas as pd

data = {
    "이름": ["김철수", "이영희", "박민수", "최지훈", "정소희"],
    "학년": [1, 2, 3, 4, 2],
    "학점": [4.2, 3.8, 4.5, 3.9, 3.5],
    "학과": ["컴퓨터공학", "경영학", "전자공학", "의학", "심리학"],
    "동아리": ["프로그래밍", "독서토론", "로봇공학", "봉사활동", "음악감상"]
}
df = pd.DataFrame(data)

## 특정 열 선택
selected_col = df[['이름', '학과', '학점']]
selected_col
# df['이름'] 단일 열 출력
# df[['이름', '학과']] 여러 열 출력. 리스트로 묶음

## DataFrame 열순서 변경
reordered_cols = df[['학과', '이름', '학년', '학점', '동아리']]
reordered_cols

## DataFrame 열이름 변경
df_renamed = df.rename(columns = {'이름': '학생명', '학점': '평점', '동아리': '과외활동'})
df_renamed

   학생명  학년   평점     학과   과외활동
0  김철수   1  4.2  컴퓨터공학  프로그래밍
1  이영희   2  3.8    경영학   독서토론
2  박민수   3  4.5   전자공학   로봇공학
3  최지훈   4  3.9     의학   봉사활동
4  정소희   2  3.5    심리학   음악감상

### 6-3 DataFrame 행 선택

In [ ]:
import pandas as pd

data = {
    "이름": ["김철수", "이영희", "박민수", "최지훈", "정소희"],
    "학년": [1, 2, 3, 4, 2],
    "학점": [4.2, 3.8, 4.5, 3.9, 3.5],
    "학과": ["컴퓨터공학", "경영학", "전자공학", "의학", "심리학"],
    "동아리": ["프로그래밍", "독서토론", "로봇공학", "봉사활동", "음악감상"]
}

#DataFrame 인덱스 지정

#DataFrame 행 선택

#DataFrame 위치 기반 행 선택

#DataFrame 조건 기반 선택

### 6-4 DataFrame 정렬

In [ ]:
import pandas as pd

data = {
    "이름": ["김철수", "이영희", "박민수", "최지훈", "정소희"],
    "학년": [1, 2, 3, 4, 2],
    "학점": [4.2, 3.8, 4.5, 3.9, 3.5],
    "학과": ["컴퓨터공학", "경영학", "전자공학", "의학", "심리학"],
    "동아리": ["프로그래밍", "독서토론", "로봇공학", "봉사활동", "음악감상"]
}

#DataFrame 인덱스 지정

#DataFrame 단일 열 오름차순, 내림차순 정렬

#DataFrame 복수 열 오름차순, 내림차순 정렬

#DataFrame 인덱스 기분 오른차순, 내림차순 정렬

## 6-5 실습 시나리오 - Kaggle을 활용한 데이터 수집 및 측정

- Kaggle([https://www.kaggle.com](https://www.kaggle.com)) 회원 가입
- Kaggle 접근 토큰 생성(API 키)

### Kaggle API 키 업로드

In [ ]:
from google.colab import files
files.upload()

### Kaggle API 키 사용을 위한 Colab 환경 설정

In [ ]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

### Kaggle 데이터셋 다운로드

In [ ]:
!kaggle competitions download –c store-sales-time-series-forecasting

!unzip store-sales-time-series-forecasting.zip

### Kaggle 데이터셋 DataFrame 로드 및 살펴보기

In [ ]:
import pandas as pd

# Grocery Sales 데이터 DataFrame 로드

# 판매 데이터 살펴보기

### Kaggle 데이터셋 측정

In [ ]:
# 판매 데이터 기본 통계량

# 매장 데이터 기본 정보

# 원유 가격 데이터 기본 정보